<div class="cec-address" itemscope itemtype="http://schema.org/Organization"> <span itemprop="name" class="hidden">Address Management - Cheshire East Council</span> <a href="mailto:addressmanagement@cheshireeast.gov.uk"><span itemprop="email">addressmanagement@cheshireeast.gov.uk</span></a><br /><br />
  <span itemprop="telephone">01270 686770</span><br /><br />
  <div itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
    <span>Address Management</span><br />
    <span>Development Management</span><br />
    <span itemprop="streetAddress">Delamere House<br />Delamere Street</span><br />
    <span itemprop="addressLocality">Crewe</span><br />
    <span itemprop="addressRegion">Cheshire</span><br />
    <span itemprop="postalCode">CW1 2LL</span>
  </div>
</div>