<div class="cec-address" itemscope itemtype="http://schema.org/Organization"> <span itemprop="name" class="hidden">Building Control - Cheshire East Council</span> <a href="mailto:BuildingControl@cheshireeast.gov.uk"><span itemprop="email">BuildingControl@cheshireeast.gov.uk</span></a><br />
  <br />
  <span itemprop="telephone">01270 375256</span><br />
  <br />
  <div itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
    <span>Building Control</span><br />
    <span itemprop="streetAddress">C/O Delamere House <br />
    Delamere Street</span><br />
    <span itemprop="addressLocality">Crewe</span><br />
    <span itemprop="addressRegion">Cheshire</span><br />
    <span itemprop="postalCode">CW1 2LL</span>
  </div>
</div>