<div class="cec-address" itemscope itemtype="http://schema.org/Organization"> <span itemprop="name" class="hidden">Business Generation Centres</span>
<span itemprop="Business Generation">Business Generation Centres</span><br /><br />
<a href="mailto:property@cheshireeast.gov.uk"><span 
itemprop="email">property@cheshireeast.gov.uk</span></a><br />
  <br />
  <span itemprop="telephone">01270 686888</span><br />
</div>