<div class="cec-address" itemscope itemtype="http://schema.org/Organization"> <span>Business Support Team<br />
  Cheshire East Council</span> <br />
	<br />
	<span itemprop="name" class="hidden">Business Support Team - Cheshire East Council</span>
	<a href="mailto:tradingstandards@cheshireeast.gov.uk"><span itemprop="email">tradingstandards@cheshireeast.gov.uk</span></a><br />
	<br />
	<span itemprop="telephone">0300 123 5015</span><br />
	<br />
</div>