<h2>Contact Business Rates</h2>
<div class="cec-address" itemscope itemtype="http://schema.org/Organization"> <span itemprop="name" class="hidden">Revenues Service - Cheshire East Council</span> <a href="https://digital-core.cheshireeast.gov.uk/w/webpage/request?form=contact_us_about_business_rates">Contact us <span class="hidden">about Business Rates enquiry form</span></a><br>
  <br>
  <p>Customer Service Business Rates Team available for telephone enquiries:<br>
    Monday - Friday, 9am to 1pm</p>
  <br />
  <span itemprop="telephone">0300 123 5013</span>
  <br />
  <div itemprop="address" itemscope itemtype="http://schema.org/PostalAddress"> <span>Revenues Service</span><br />
    <span>Cheshire East Council</span><br />
    <span itemprop="streetAddress">PO Box 622</span><br />
    <span itemprop="addressLocality">Crewe</span><br />
    <span itemprop="addressRegion">Cheshire</span><br />
    <span itemprop="postalCode">CW1 9JH</span>
  </div>
</div>