<div class="light-turquoise px-4 pt-3 mb-4">
	<h2 class="aside-heading"><span class="aside-heading-txt">Contact details</span></h2>
<address class="p-2 mb-0">
<div class="cec-address" itemscope itemtype="http://schema.org/Organization"> <span itemprop="name" class="hidden">Cheshire East Mobile Children's Centre</span> <a href="mailto:mobilechildrenscentre@cheshireeast.gov.uk"><span itemprop="email">mobilechildrenscentre@cheshireeast.gov.uk</span></a><br />
  <br />
  <span itemprop="telephone">0300 123 5033</span><br />
  <br />
</div>
</address></div>