<h2>Contact the Citizenship Registrar</h2>
<div class="cec-address" itemscope itemtype="http://schema.org/Organization"> <span itemprop="name" class="hidden">Cheshire East Register Offices</span>
  <p>Email: </p><a href="mailto:csc@cheshireeast.gov.uk"><span itemprop="email">csc@cheshireeast.gov.uk</span></a>
  <p>All citizenship ceremonies take place at the Municipal Buildings, Earle Street, Crewe.</p>
</div>