<div class="cec-address" itemscope itemtype="http://schema.org/Organization"> <span itemprop="name" class="hidden">Countryside Ranger Service - Cheshire East Council</span>
  <h2>Contact Ranger service</h2>
  <a href="mailto:rangers@cheshireeast.gov.uk"><span itemprop="email">rangers@cheshireeast.gov.uk</span></a><br />
  <br />
  <p>For Middlewood Way, Jacksons’ Brickworks, Poynton Coppice and Poynton Park: phone 01625 383700</p>
  <p>For Tegg’s Nose Country Park: phone 01625 374833</p>
  <p>For Lindow Common or Macclesfield Riverside Park: phone 01625 374790</p>

  <p>For Brereton Heath Local Nature Reserve, Dane-In-Shaw Pasture SSSI, Croxton Park, Biddulph Valley Way, Timbersbrook Picnic Area, Salt Line, Borrow Pit Meadows, Wheelock Rail Trail, Merelake Way and Rode Heath Rise: phone 01477 534115</p>

  <p>For Gritstone Trail: phone 01270 686029</p>
</div>