<h2 id="contact"> Contact Council Tax</h2>
<p>
	<a href="https://digital-core.cheshireeast.gov.uk/w/webpage/request?form=contact_us_about_council_tax&Service=DTC0001969GBFRF1">
		Council Tax enquiry form
	</a>
</p>
<p>If you're unable to use our forms or have any questions about your bill you can call the Council Tax Customer Service Team on 0300 123 5013 between 8:30am to 4pm, Monday to Friday, excluding bank holidays.</p>