<H2>Contact Development Management - Planning</H2>
<div class="cec-address" itemscope itemtype="http://schema.org/Organization"> <span itemprop="name" class="hidden">Development Management - Cheshire East Council</span>
	<a href="mailto:planning@cheshireeast.gov.uk"><span itemprop="email">planning@cheshireeast.gov.uk</span></a><br />
	<br />
	<span itemprop="telephone">0300 123 5014</span><br />
	<br />
	<div itemprop="address" itemscope itemtype="http://schema.org/PostalAddress"> <span><strong>Development Management</strong></span><br />
		<span>Cheshire East Council</span><br />
		<span itemprop="streetAddress">PO Box 606</span><br />
		<!--<span itemprop="streetAddress">Municipal Buildings</span><br />-->
		<span itemprop="addressLocality">Crewe</span><br />
		<span itemprop="addressRegion">Cheshire</span><br />
		<span itemprop="postalCode">CW1 9HP</span>
	</div>
</div>