<div class="cec-address" itemscope itemtype="http://schema.org/Organization"> <span itemprop="name" class="hidden">Electoral Services - Cheshire East Council</span> <a href="mailto:electoral.information@cheshireeast.gov.uk"><span itemprop="email">electoral.information@cheshireeast.gov.uk</span></a><br />
  <br />
  <span itemprop="telephone">0300 123 5016</span><br />
  <br />
  <div itemprop="address" itemscope itemtype="http://schema.org/PostalAddress"> <span>Electoral Services</span><br />
    <span itemprop="streetAddress">Macclesfield Town Hall <br />
    C/O Delamere House</span><br />
    <span itemprop="streetAddress">Delamere Street</span><br />
    <span itemprop="addressLocality">Crewe</span><br />
    <span itemprop="addressRegion">Cheshire</span><br />
    <span itemprop="postalCode">CW1 2LL</span>
  </div>
</div>