<div class="cec-address"> <span> <a title="Emergency Assistance contact form" href="https://digital-core.cheshireeast.gov.uk/w/webpage/request?form=contact_us&Service=DTC0001967GBFRF1">Emergency Assistance contact form</a></span><br />
	<br />
	<span>0300 123 5013</span><br />
	<br />
	<span>Benefits Section</span><br />
	<span>Cheshire East Council</span><br />
	<span>PO Box 622</span><br />
	<span>Earle Street</span><br />
	<span>Crewe</span><br />
	<span>Cheshire</span><br />
	<span>CW1 9JH</span>
</div>