<div class="vcard">
 <span class="fn"></span>
 <p class="org">Local Plan matters only</p>
 <p><a class="email" title="localplan@cheshireeast.gov.uk" href="mailto:localplan@cheshireeast.gov.uk">Email Local Plan Team</a></p>
 <p class="tel">01270 685893</p>
 </div><!-- /vcard -->
 <hr />
 
 <div class="vcard">
 <span class="fn"></span>
<p class="org">All other planning enquiries (including planning application queries)</p>
 <p><a class="email" title=planning@cheshireeast.gov.uk href="mailto:planning@cheshireeast.gov.uk">Email Planning Department</a></p>
 <p class="tel">0300 123 5014</p>
 </div><!-- /vcard -->
 
 
 
 