<DIV class=vcard>
	<A class=email title=ncrm@childrenssociety.org.uk href="mailto:participation@cheshireeast.gov.uk ">Email November children's rights month</A>
	<BR>
	<BR>
	<P>
		<A title="(external link)" href="https://en-gb.facebook.com/CheshireEastCouncil/">Facebook -November children’s rights month</A>
	</P>
	<P>Twitter:
		<A href="https://twitter.com/cheshireeast">@cheshireeast</A>
	</P>
</DIV>