<div class="cec-address" itemscope itemtype="http://schema.org/Organization"> <span itemprop="name" class="hidden">Transport Policy and Accessibility - Cheshire East Council</span>
	<a href="mailto:activetravel@cheshireeast.gov.uk"><span itemprop="email">transportpolicy@cheshireeast.gov.uk</span></a><br />
	<br />
	<span itemprop="telephone">01270 686349</span><br />
	<br />
	<span>Monday to Friday 8:30am to 5pm</span><br />
	<br />
	<div itemprop="address" itemscope itemtype="http://schema.org/PostalAddress"> <span>Transport Service Solutions</span><br />

		<span itemprop="streetAddress">Cledford Lane</span><br />
		<span itemprop="streetAddress">Middlewich</span><br />
		<span itemprop="addressLocality">Cheshire</span><br />

		<span itemprop="postalCode">CW10 0JR</span>
	</div>
	<br />
	<br />
	<p>For Bus and Train times call Traveline <br /> 0871 200 22 33 calls cost 10p per minute plus network extras <br /> open 7 days a week 8am to 8pm closed Christmas Day, Boxing Day and New Years Day</p>
</div>