<div class="cec-address" itemscope itemtype="http://schema.org/Organization"> <span itemprop="name" class="hidden">School transport team</span>
	<a href="mailto:schooltransport@cheshireeast.gov.uk"><span itemprop="email">schooltransport@cheshireeast.gov.uk</span></a><br />
	<br />
	<span itemprop="Phone">0300 123 5012</span><br />
	<P>Monday to Friday 8:30am to 5pm Monday to Friday excluding Bank Holidays </P>
</div>