<div class="cec-address" itemscope itemtype="http://schema.org/Organization"> <span itemprop="name" class="hidden">School Admissions - Cheshire East Council</span>
	<a href="mailto:admissions@cheshireeast.gov.uk"><span itemprop="email">admissions@cheshireeast.gov.uk</span></a><br />
	<br />
	<span itemprop="telephone">Phone: 0300 123 5012 -  option 1</span><br />
	<br />
	<div itemprop="address" itemscope itemtype="http://schema.org/PostalAddress"> <span>School Admissions </span><br />
		<span itemprop="streetAddress">Floor 1, Delamere House</span> <br />
		<span itemprop="streetAddress">Delamere Street</span> <br />
		<span itemprop="addressLocality">Crewe</span><br />
		<span itemprop="addressRegion">Cheshire</span><br />
		<span itemprop="postalCode">CW1 2LL</span>
	</div><br />
</div>