<div class="cec-address" itemscope itemtype="http://schema.org/Organization"> <span itemprop="name" class="hidden">School Organisation and Capital Strategy - Cheshire East Council</span> <span>School Organisation and Capital Strategy <br />
  Cheshire East Council</span><br />
  <br />
  <a href="mailto:SOCS@cheshireeast.gov.uk"><span itemprop="email">SOCS@cheshireeast.gov.uk</span></a><br />
  <br />
  <span itemprop="telephone">0300 123 5012</span><br />
  <br />
  Fax: <span itemprop="faxNumber">01270 6864911</span><br />
</div>