<div class="cec-address" itemscope itemtype="http://schema.org/Organization"> <span itemprop="name" class="hidden">Attendance and Children Out of School</span> <a href="mailto:childemployment@cheshireeast.gov.uk"><span itemprop="email">childemployment@cheshireeast.gov.uk</span></a><br />
  <br />
  <span itemprop="telephone">01270 686199</span><br />
  <br />
  <div itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
    <span>Entertainment and Employment Team</span><br />
    <span>Attendance and Children Out Of School Service</span><br />
    <span itemprop="streetAddress">Floor 1 Delamere House, Delamere Street<br />
    <span itemprop="addressLocality">Crewe</span><br />
    <span itemprop="addressRegion">Cheshire</span><br />
    <span itemprop="postalCode">CW1 2LL</span>
  </div>
</div>