<div class="cec-address" itemscope itemtype="http://schema.org/Organization"> <span itemprop="name" class="hidden">Supported Employment - Cheshire East Council</span> <a href="mailto:supportedemployment@cheshireeast.gov.uk"><span itemprop="email">supportedemployment@cheshireeast.gov.uk</span></a><br />
  <br />
  <span itemprop="telephone">01260 375468</span><br />
  <br />
  <div itemprop="address" itemscope itemtype="http://schema.org/PostalAddress"> <span>Supported Employment Services</span><br />
    <span itemprop="streetAddress">Macclesfield Town Hall</span><br />
    <span itemprop="streetAddress">Market Place</span><br />
    <span itemprop="addressLocality">Macclesfield</span><br />
    <span itemprop="addressRegion">Cheshire</span><br />
    <span itemprop="postalCode">SK10 1EA</span></div>
</div>