<h2>Contact Waste and Recycling</h2>
<div class="cec-address" itemscope itemtype="http://schema.org/Organization"> <span itemprop="name" class="hidden">Waste and Recycling - Cheshire East Council</span>
	<a href="https://digital-core.cheshireeast.gov.uk/w/webpage/request?form=contact_us&Service=DTC0001982GBFRF1">Contact us about waste and recycling</a>
	<p>Call our Waste and Recycling Customer Service Team on <span itemprop="telephone">0300 123 5011</span> during office hours, 8:30am to 5pm Monday to Friday, if you're unable to use our form.</p>
</div>